[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = true

[programs.devnet]
pumpfun = "ApRXrsZcqKHzQFrdYYKcPhe66S5oHMwWqnC9DZVqiZFM"

[programs.localnet]
pumpfun = "ApRXrsZcqKHzQFrdYYKcPhe66S5oHMwWqnC9DZVqiZFM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=7387c4ee-fe6a-43a6-96ea-05e6534aa500"
wallet = "./keys/admin.json"

[scripts]
build = "rm -rf target && anchor build && mkdir -p target/deploy && cp ./keys/program/3uHJMHzeiqdqQ3LNc5bNVxuCp224HGtStPkv1JUEcabr.json ./target/deploy/pumpfun-keypair.json"
build-with-so = "anchor run build && ln -s $HOME/.cargo/target/sbf-solana-solana/release/pumpfun.so $PWD/target/deploy/pumpfun.so"
test = "./tests/anchor-tests-runner.sh"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "spl-programs/metadata.so"
